---
title: "The Dow Jones Distortion Index"
subtitle: "Index construction methodology - additional details"
layout: default
tags: [R, finance, index, equity]
permalink: /references/DJDI_methodology
---

# Dow Jones Distortion Index - additional details
_The following provides additional details for my original post on the Dow Jones Distortion Index [here](http://eightportions.com/2016-06-15-Dow-Jones-Distortion-Index)._

## Methodology details
The Dow Jones Distortion Index ("DJDI") is defined as half of the sum of the absolute difference between each stock's price-weighted contribution to the Dow Jones Industrial Average ("DJIA") and its share of the DJIA total market cap. Let $$P_n$$ equal the price of stock $$n$$ and $$M_n$$ equal the market capitalization of stock $$n$$ on any given day. The DJDI is calculated as:

$$DJDI = \frac{1}{2}\sum_{n=1}^{N} |P^*_n - M^*_n|$$

where $$P^*_n = \frac{P_n}{\sum_{i=1}^{N} P_i}$$ is the share of the sum price of the DJIA components contributed by stock $$n$$, $$M^*_n = \frac{M_n}{\sum_{i=1}^{N} M_i}$$ is the share of the total market cap of the DJIA components contributed by stock $$n$$, and $$N$$ is the number of stocks comprising the DJIA (currently $$N = 30$$).

### Real example: May 27, 2016
The following table illustrates how the DJDI is calculated, stock-by-stock, for May 27, 2016:
```{r kable, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
library(knitr, quietly = TRUE)
library(scales, quietly = TRUE)
library(data.table, quietly = TRUE)
library(lubridate, quietly = TRUE)

data_path <- "/Volumes/HDD/DJIA/2.Data/"
mkt_cap <- fread(paste0(data_path, "DJ_mkt_cap.csv"))[date == mdy("5/27/2016")]
mkt_cap$abs_share_diff <- abs(mkt_cap$sop - mkt_cap$som)

df_short <- mkt_cap[, .(ticker, mkt_cap, som, price = price_unadj, sop, abs_share_diff)]
total <- c("DJDI", "", "", "", "", percent(sum(df_short[,abs_share_diff])/2))

df_short$mkt_cap <- dollar(df_short$mkt_cap/1000)
df_short$som <- percent(df_short$som)
df_short$price <- dollar(df_short$price)
df_short$sop <- percent(df_short$sop)
df_short$abs_share_diff <- percent(df_short$abs_share_diff)

names(df_short) <- c("Ticker", "Market Cap (BN)", "[M] Share of sum market cap", "Price", "[P] Share of sum price", "Absolute difference (P - M)")
df_short <- df_short[order(df_short$Ticker),]
df_short <- rbind(as.data.frame(df_short), total)

kable(df_short, digits = 2, row.names = FALSE)
```
